# Generated by Django 2.0 on 2018-03-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=400)),
                ('number_of_pages', models.IntegerField(max_length=5)),
                ('year_of_publication', models.DateField()),
                ('genre', models.CharField(max_length=200)),
                ('is_favourite', models.BooleanField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
