# Generated by Django 2.0 on 2018-03-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.FileField(default='settings.MEDIA_ROOT/books_cover/default.png', upload_to='books_cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(),
        ),
    ]
