# Generated by Django 2.0 on 2018-03-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180324_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('picture', models.FileField(default='settings.MEDIA_ROOT/authors/default.png', upload_to='authors')),
            ],
        ),
    ]
