# Generated by Django 2.0 on 2018-03-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180324_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.FileField(upload_to='authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.FileField(upload_to='books_cover'),
        ),
    ]
