# Generated by Django 2.0 on 2018-03-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20180324_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.FileField(default='authors/default.png', upload_to='authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.FileField(default='books_cover/default.png', upload_to='books_cover'),
        ),
    ]
