# Generated by Django 2.0 on 2018-03-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.FileField(default='defaulta.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.FileField(default='default.png', upload_to=''),
        ),
    ]
